BUGFIX: missing import statement in __init__.py
SMTG-UCL/galore pull request #37
Opened 2021-06-28 13:33 UTC by Yaxuan-Lii

This is a copy of #34. Because of the wrong branch name.

2021-06-28 14:13 UTC, ajjackson commented
This looks promising, the tests failed due to ImportError as expected. Now it can be fixed and we willl be a bit more confident that the fix did something!

2021-06-30 16:07 UTC, ajjackson commented
The last commit "fix the imports" seems to add a lot of unnecessary files to the project. Probably they were added accidentally. Can you clean that up?

2021-07-01 02:52 UTC, Yaxuan-Lii reviewed
But fail to delete them.

2021-07-02 14:33 UTC, ajjackson requested changes
I'll clean up the missing files tonight, here are a couple of other things to look at.

2021-07-02 14:33 UTC, ajjackson commented on test/test_process_pdos.py
> +    def test_lorentzian(self):
test_lorentzian and test_broaden don't test `process_pdos` so I don't think they belong in this class?

2021-07-02 14:33 UTC, ajjackson commented on test/test_process_pdos.py
> +
There are Python conventions for how many blank lines should be between sections; try running `flake8` on this file.

2021-07-06 14:54 UTC, ajjackson commented on test/test_process_pdos.py
> +    def test_lorentzian(self):
Still, they appear to be new tests and it's good to test them _somewhere_. Really the test suite could use a bit of modernisation (Pytest maybe?) So for now let's keep them.

2021-07-06 15:30 UTC, ajjackson approved these changes

2021-07-06 15:39 UTC, merged